### PR TITLE
update for local dev env

### PR DESCRIPTION
**Pull request by yu23ki14**

### CODE REVIEW

**Comment by alecrem** [comment]
Sorry, I was implementing 50% of this on #21, only in a different way.

Keeping consistent with omise, on #21 contract addresses are hardcoded onto a ts file. I don't think we need to consider them secrets, so having them on the repo can make environments easier.

Do you think .env is better?

**Comment by yu23ki14** [comment]
@alecrem 
We need to use local net HenkakuV2 contract address for interacting with Nengajo contract. So using .env.local is good way to handle main net and local net. It's not for hide addresses.

**Comment by alecrem** [comment]
@yu23ki14 I understand editing .env.local can be more convenient for the local addresses than editing a longer file.

But I would like to avoid putting the testnet and mainnet addresses on .env.local. I think it's more convenient if those are on the repo.

What do you think about this idea? We merge this so that it's easier to work with hardhat, and after that I redo my PR taking the .env.local value from contractAddress.ts, but only if it's the local chain.

**Review by alecrem — APPROVED** [review]
LGTM

**Pull request merged**
