### PR TITLE
Update wagmi 0.7.7 to 0.8.4

### PR DESCRIPTION
**Pull request by dueyama**
it looks yarn.lock is also updated. is it wrong?

### CODE REVIEW

**Comment by alecrem** [comment]
> it looks yarn.lock is also updated. is it wrong?

This is correct. `yarn.lock` tracks the installed versions of all packages.

Updating wagmi triggered a cascade of updates because of the slightly different dependencies of the new version.

**Comment by dueyama** [comment]
understand.

**Review by alecrem — APPROVED** [review]
LTGM

**Comment by alecrem** [comment]
@dueyama If you add "Closes #12" on the PR description, the issue will be automatically closed when the PR is merged.

**Pull request merged**
